### ISSUE TITLE
Arena statistics support.

### ISSUE THREAD

**Issue by heyitsbench** [FrancescoBorzi/PvPstats#19]
On AzerothCore, relevant statistics are logged in `log_arena_fights`, and `log_arena_memberstats`, not sure about other cores. Would it be possible to extend the functionality of this repo to arenas as well?

**Comment by FrancescoBorzi** [comment]
hey @heyitsbench , yes would be nice to have statistics for Arenas but the PvPstats is quite an old application that I've written 10 years ago and it is a monolith (frontend+backend together) written with old PHP and plain HTML.

I would not extend this app to add new features, instead I'd create new apps.

There is something we previously did for Arenas too, which is https://github.com/azerothcore/arena-stats
This is also a bit outdated, but still more modern than the PvPstats (and not a monolith).

I'd rater update/extend the existing arena-stats app, or create a new one, rather than extending the PvPstats.
